### ISSUE TITLE
Test BLE Nano 2

### ISSUE THREAD

**Issue by oowais** [oowais/Jaadu#19]
How it works,
how its bluetooth works
how its software uploaded

**Comment by oowais** [comment]
https://github.com/redbear/nRF5x

https://github.com/redbear/nRF5x/blob/341f6adff63fafefc474e927af3af260d3977004/arduino/arduino-1.8.0/hardware/RBL/RBL_nRF52832/libraries/BLE_Examples/examples/SimpleChat/SimpleChat.ino

**Comment by oowais** [comment]
Install Nano V2 board on Arduino Software: https://github.com/redbear/nRF5x/blob/master/nRF52832/docs/Arduino_Board_Package_Installation_Guide.md

**Comment by oowais** [comment]
All about Nano v2
https://github.com/redbear/nRF5x/tree/master/nRF52832

**Comment by oowais** [comment]
Initial testing worked! able to connect to Android Bluetooth via [nRF Toolbox](https://play.google.com/store/search?q=nrf%20toolbox)

**Comment by oowais** [comment]
[Product Specifications](http://infocenter.nordicsemi.com/pdf/nRF52832_PS_v1.4.pdf)

**Comment by dvaruas** [comment]
DAPLink : DAPLink_V1.0_Interface_nRF52.bin
Bootloader : SoftdeviceS132_2.0_SDK11_Bootloader_20161221.hex

To install bootloader, first press reset button on the DAPLink and then drag-n-drop bootloader.

BLE Nano v2 uses 32-bit architecture.. So need to install 32-bit specific libraries to compile arduino codes.. 

Host OS : Ubuntu 18.04
Arduino IDE : 1.8.7

Initial setup steps - https://github.com/redbear/nRF5x/blob/master/nRF52832/docs/Arduino_Board_Package_Installation_Guide.md

To make upload in Arduino IDE successful steps - 
1. sudo dpkg --add-architecture i386
2. sudo apt-get update
3. sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 libudev1:i386 multiarch-support
