### ISSUE TITLE
Designing Eye expressions

### ISSUE THREAD

**Issue by oowais** [oowais/Jaadu#23]
eye expression on different emotions displayed by the Alien

**Comment by oowais** [comment]
Using Adafruit library to use Adafruit backpack
[Github Link](https://github.com/adafruit/Adafruit_Python_LED_Backpack) 

Enable i2c and spi interface(if required) in raspi-config from [here](https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c)

**Comment by oowais** [comment]
The Adafruit library might move to a new build using circuitpython

- [CircuitPython & RasPi](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/circuitpython-raspi)
- [Adafruit_CircuitPython_HT16K33](https://github.com/adafruit/Adafruit_CircuitPython_HT16K33)
- [It's releases](https://github.com/adafruit/Adafruit_CircuitPython_HT16K33/releases)

**Comment by the4daspect** [comment]
Eye Designs: https://drive.google.com/open?id=1b9J6JqygPaHC_PervrXMHkVKXhiJLlnc

**Comment by oowais** [comment]
Added for raspi and arduino(test) both
