### ISSUE TITLE
Design Hand glove/bracelet

### ISSUE THREAD

**Issue by oowais** [oowais/Jaadu#29]
Use Cloth/available glove online

**Comment by oowais** [comment]
Possible options for wrist supprort:

- [Handbandage-verstauchungen-sehnenscheidenentz](https://www.amazon.de/Actesso-Handgelenkbandage-Handbandage-verstauchungen-sehnenscheidenentz%C3%BCndung/dp/B01D02VLOI/ref=sr_1_9_sspa?ie=UTF8&qid=1545302897&sr=8-9-spons&keywords=medical+wrist&psc=1)
- [Handgelenkschiene-Karpaltunnel](https://www.amazon.de/Actesso-Handgelenk-Bandagen-Handgelenkschiene-Karpaltunnel/dp/B007M2KEAA/ref=sr_1_13?ie=UTF8&qid=1545302897&sr=8-13&keywords=medical+wrist)
- [Handgelenkschiene-Karpaltunnel-fraktur-Zerrungen](https://www.amazon.de/Actesso-Handgelenkschiene-Karpaltunnel-fraktur-Zerrungen/dp/B008JE732M/ref=sr_1_19_sspa?ie=UTF8&qid=1545302897&sr=8-19-spons&keywords=medical+wrist&psc=1)

**Comment by the4daspect** [comment]
we will be using the glove that we buyed.
